// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/app/components/navbar";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-white text-black antialiased">
        <div className="fixed top-0 w-full z-50">
          <NavBar />
        </div>
        <main className="pt-[64px]">{children}</main>
      </body>
    </html>
  );
}
