import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navbar";
import BackToTop from "@/app/components/BackToTop"; // Add this line

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "He Kai's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // <- path in your public/ folder
    apple: "/apple-touch-icon.png", // optional
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <div className="fixed top-0 w-full z-50">
          <Navbar />
        </div>
        <main className={`pt-[64px]`}>{children}</main>
        <BackToTop /> {/* Add this line */}
      </body>
    </html>
  );
}
